
# Croatia, (July 2020)

# The label "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP HRVATSKA SELJAČKA STRANKA
# - HSS HRVATSKA STRANKA UMIROVLJENIKA - HSU SNAGA - STRANKA NARODNOG I
# GRAĐANSKOG AKTIVIZMA - SNAGA GRAĐANSKO-LIBERALNI SAVEZ - GLAS ISTARSKI
# DEMOKRATSKI SABOR - IDS PRIMORSKO GORANSKI SAVEZ - PGS" is coded as both pty
# == 5168 and pty == 5169 in this election. I use 5168.

dta$pty[
  dta$id == 2045 &
    dta$pty_n == "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP HRVATSKA SELJAČKA STRANKA - HSS HRVATSKA STRANKA UMIROVLJENIKA - HSU SNAGA - STRANKA NARODNOG I GRAĐANSKOG AKTIVIZMA - SNAGA GRAĐANSKO-LIBERALNI SAVEZ - GLAS ISTARSKI DEMOKRATSKI SABOR - IDS PRIMORSKO GORANSKI SAVEZ - PGS"
] <- 5168
